### ISSUE TITLE
NEW PAPER: STLLaVA-Med

### ISSUE THREAD

**Issue by canqin001** [richard-peng-xia/awesome-multimodal-in-medical-imaging#16]
Hi Richard,

Thanks for your amazing collection of medical multimodal works. We recently have a new related paper accepted by EMNLP24 (Main) and it is fully open-sourced. Could you please add this work to your list? Thank you so much for your kind help.

Paper: https://arxiv.org/abs/2406.19973
Code: https://github.com/heliossun/STLLaVA-Med
HF: https://huggingface.co/ZachSun/stllava-med-7b

Regards,
Can

**Comment by richard-peng-xia** [comment]
Hi @canqin001,

I have already added your paper since last commit. And I will update its publication.

Thanks for your advice.

**Comment by canqin001** [comment]
Great and thank you!
